const types = {

    TASKLIST_CREATE: 'TASKLIST_CREATE',
    TASKLIST_DELETE: 'TASKLIST_DELETE',
    TASKLIST_UPDATE: 'TASKLIST_UPDATE',

    TASK_CREATE: 'TASK_CREATE',
    TASK_UPDATE: 'TASK_UPDATE',
    TASK_DELETE: 'TASK_DELETE'
}

export default types


